# Generated by Django 3.1.7 on 2023-07-13 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('income_app', '0004_auto_20230629_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.localtime)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='income_app.income')),
            ],
        ),
    ]
