# Generated by Django 3.1.7 on 2023-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
