# Generated by Django 3.1.7 on 2023-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_auto_20230629_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
