# Generated by Django 3.1.7 on 2023-08-24 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0004_expense_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.localtime)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('created_by', models.TextField()),
            ],
        ),
    ]
