# Generated by Django 3.1.7 on 2023-08-25 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0005_fuelexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelexpense',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
