# Generated by Django 3.1.7 on 2023-08-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0006_auto_20230825_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelExpense',
        ),
    ]
