# Generated by Django 3.1.7 on 2023-08-24 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField()),
                ('fuel_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_charges', models.DecimalField(decimal_places=2, max_digits=5)),
                ('incentive', models.PositiveSmallIntegerField()),
                ('amount_payable', models.PositiveIntegerField()),
                ('rider_name', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=10)),
                ('fuel_date', models.DateField(default=django.utils.timezone.localtime)),
                ('origin_array', models.JSONField()),
                ('destination_array', models.JSONField()),
                ('distances_array', models.JSONField()),
            ],
        ),
    ]
