# Generated by Django 3.1.7 on 2023-08-24 17:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_calculator_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='fuelcalculator',
            name='fuel_rate',
        ),
        migrations.AlterField(
            model_name='fuelcalculator',
            name='destination_array',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='fuelcalculator',
            name='distances_array',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='fuelcalculator',
            name='origin_array',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
