# Generated by Django 3.1.7 on 2023-08-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_calculator_app', '0002_auto_20230824_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcalculator',
            name='destination_array',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='fuelcalculator',
            name='distances_array',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='fuelcalculator',
            name='origin_array',
            field=models.JSONField(),
        ),
    ]
