# Generated by Django 3.1.7 on 2023-08-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_calculator_app', '0004_auto_20230825_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcalculator',
            name='amount_payable',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fuelcalculator',
            name='incentive',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
