# Generated by Django 3.1.7 on 2023-08-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0007_delete_fuelexpense'),
        ('fuel_calculator_app', '0005_auto_20230827_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcalculator',
            name='expense_obj',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='expense_app.expense'),
            preserve_default=False,
        ),
    ]
