# Generated by Django 3.1.7 on 2023-09-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_calculator_app', '0006_fuelcalculator_expense_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='idling_factor',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
        ),
        migrations.AddField(
            model_name='fuel',
            name='maintenance_factor',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
    ]
