# Generated by Django 3.1.7 on 2023-06-22 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='PKR - Pakistani Rupee', max_length=255)),
                ('profile_pic', models.ImageField(blank=True, upload_to=user_profile.models.user_path)),
                ('email_preference', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
