# Generated by Django 3.1.7 on 2023-08-14 15:55

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20230814_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=user_profile.models.user_path),
        ),
    ]
