# Generated by Django 3.1.7 on 2023-06-29 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('income_app', '0002_auto_20230629_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=django.utils.timezone.localtime),
        ),
    ]
