# Generated by Django 3.1.7 on 2023-06-29 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('income_app', '0003_auto_20230629_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesource',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
