# Generated by Django 3.1.7 on 2023-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_app', '0004_auto_20230629_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='created_by',
            field=models.TextField(default='value'),
            preserve_default=False,
        ),
    ]
