# Generated by Django 3.1.7 on 2023-07-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartover_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Low', max_length=100),
        ),
    ]
