# Generated by Django 3.1.7 on 2023-07-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartover_app', '0002_auto_20230718_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
    ]
