# Generated by Django 3.1.7 on 2023-07-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartover_app', '0003_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creation_date',
            new_name='date',
        ),
    ]
