# Generated by Django 3.1.7 on 2023-07-19 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartover_app', '0004_auto_20230718_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_closer', to=settings.AUTH_USER_MODEL),
        ),
    ]
