# Generated by Django 3.1.7 on 2023-08-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartover_app', '0006_remove_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
